# Holiday specifications

It's time to book your summer holidays. You've put some details into a price comparison website and now you've got umpty-thousand holiday suggestions to look at, most of which are rubbish.

You need to whittle down the options.

The file [00-prices.txt](00-prices.txt) contains what you've got from the price comparison website. 

It's a simple text file, with one possible holiday package per line.

Each line has four fields, separated by spaces. They are:
* The deal ID, from the price comparison website you found it.
* The holiday price, in whole pounds.
* The location of the holiday, always a single word.
* The surcharges and extras you'll need to pay. 

However, you may be able to persuade your rich aunt to pay some of the surcharges. After all, she still thinks you're eight and gives you an apple every time you see her.

For example, the data file might look like this:

```
8992c78165 1132 Geoje-Si 587
1dbcfe08c3 1368 Parowan 207
52c6f5bab4 1305 Nullarbor 605
e6b32692e 1254 Aalborg 507
dac003fa56 1258 Tubakuba 408
01578ed4e77 1170 Geoje-Si 487
```


## Part 1
You fancy playing golf. How many holidays are at `Nullarbor`, the [Nullarbor links](https://en.wikipedia.org/wiki/Nullarbor_Links)?

In [362]:
example_holidays = [h.split() for h in 
"""8992c78165 1132 Geoje-Si 587
1dbcfe08c3 1368 Parowan 207
52c6f5bab4 1305 Nullarbor 605
e6b32692e 1254 Aalborg 507
dac003fa56 1258 Tubakuba 408
01578ed4e77 1170 Geoje-Si 487""".split('\n')]
example_holidays

[['8992c78165', '1132', 'Geoje-Si', '587'],
 ['1dbcfe08c3', '1368', 'Parowan', '207'],
 ['52c6f5bab4', '1305', 'Nullarbor', '605'],
 ['e6b32692e', '1254', 'Aalborg', '507'],
 ['dac003fa56', '1258', 'Tubakuba', '408'],
 ['01578ed4e77', '1170', 'Geoje-Si', '487']]

### Solution

In [363]:
holidays = []
with open('00-prices.txt') as f:
    for hol_line in f.readlines():
        holidays.append(hol_line.split())
        
holidays[:3]

[['d77b1148', '1396', 'Mamula', '579'],
 ['42e05169e', '1104', 'Jayuya', '476'],
 ['a6538cfa970', '1100', 'Parowan', '661']]

In [364]:
selected_holidays = []
for h in holidays:
    if h[2] == 'Nullarbor':
        selected_holidays.append(h)

len(selected_holidays)

9

In [365]:
len(holidays)

124

### Smart-alec one-line solution

In [366]:
sum(1 for h in open('00-prices.txt').readlines() if h.split()[2] == 'Nullarbor')

9

In [367]:
sum(1 for h in example_holidays if h[2] == 'Nullarbor')

1

# Part 2
What's the least you will have to spend on a holiday, given that your aunt will pay the first £500 of the surcharge?


## Example

```
8992c78165 1132 Geoje-Si 587
1dbcfe08c3 1368 Parowan 207
52c6f5bab4 1305 Nullarbor 605
e6b32692e 1254 Aalborg 507
dac003fa56 1258 Tubakuba 408
01578ed4e77 1170 Geoje-Si 487
```

Given the holiday list above, your aunt will pay all the surcharge in three holidays, so you'll only pay the base price. 

The first holiday to Geoje-Si will cost you £1132 + (£587- £500) = £1219 and the holiday to Parowan will cost just £1368, as your aunt will pick up all the surcharge. 

You can find the other prices you'll have to pay as:

|    Holiday             | Price to you |
|-------------------------------|-------|
| `8992c78165 1132 Geoje-Si 587` | 1219 |
| `1dbcfe08c3 1368 Parowan 207` | 1368 |
| `52c6f5bab4 1305 Nullarbor 605` | 1410 |
| `e6b32692e 1254 Aalborg 507` | 1261 |
| `dac003fa56 1258 Tubakuba 408` | 1258 |
| `01578ed4e77 1170 Geoje-Si 487` | 1170 |

That means the cheapest holiday you'll have to pay for is the second holiday to Goeji-Si, with code `01578ed4e77`



In [368]:
def cost_of_holiday(holiday):
    hid, cost, destination, surcharge = tuple(holiday)
    if int(surcharge) <= 500:
        eff_surcharge = 0
    else:
        eff_surcharge = int(surcharge) - 500
    cost = int(cost) + eff_surcharge
    return cost

In [369]:
best_holiday = ''
best_value = 0

for h in holidays:
    if cost_of_holiday(h) > best_value:
        best_value = cost_of_holiday(h)
        best_holiday = h[0]
        
best_holiday

'e3790f1484'

## Smart-alec solution

In [370]:
# Right answer
sorted(holidays, key=cost_of_holiday, reverse=True)[:3]

[['e3790f1484', '1682', 'Giessenmestia', '448'],
 ['443a80bb', '1286', 'Mamula', '872'],
 ['2b11e359e8f9', '1488', 'Brorfelde', '613']]

In [371]:
# Answer if you take just the base price
sorted(holidays, key=lambda h: int(h[1]), reverse=True)[:3]

[['e3790f1484', '1682', 'Giessenmestia', '448'],
 ['2b11e359e8f9', '1488', 'Brorfelde', '613'],
 ['f793130d4b2d', '1473', 'Nordkapp', '595']]

In [372]:
# Answer if you always deduct £500
sorted(holidays, key=lambda h: int(h[1]) + int(h[3]) - 500, reverse=True)[:3]

[['443a80bb', '1286', 'Mamula', '872'],
 ['e3790f1484', '1682', 'Giessenmestia', '448'],
 ['2b11e359e8f9', '1488', 'Brorfelde', '613']]

In [373]:
[h for h in holidays if h[2] == 'Mamula']

[['d77b1148', '1396', 'Mamula', '579'],
 ['cd1f4025', '1419', 'Mamula', '629'],
 ['443a80bb', '1286', 'Mamula', '872'],
 ['d4bc8ebfb', '1373', 'Mamula', '651'],
 ['f22c113c', '1217', 'Mamula', '521']]

In [374]:
1682+448

2130

In [375]:
1286+872

2158

In [376]:
1488+613

2101

In [377]:
# Right answer
min(holidays, key=cost_of_holiday)

['627824317b47', '909', 'Giessenmestia', '532']

In [378]:
# Answer if you take just the base price
min(holidays, key=lambda h: int(h[1]))

['cf8876d4e73', '823', 'Stonington-Island', '693']

In [379]:
# Answer if you always deduct £500
min(holidays, key=lambda h: int(h[1]) + int(h[3]) - 500)

['a68d97fbfdb', '987', 'Brorfelde', '451']

In [380]:
909+532

1441

In [381]:
987+459

1446

In [382]:
[['627824317b47', '909', 'Giessenmestia', '532'],
 ['a68d97fbfdb', '987', 'Brorfelde', '459'],
 ['be8b9d110', '984', 'Tubakuba', '485']]

[['627824317b47', '909', 'Giessenmestia', '532'],
 ['a68d97fbfdb', '987', 'Brorfelde', '459'],
 ['be8b9d110', '984', 'Tubakuba', '485']]

In [383]:
# Right answer
sorted(example_holidays, key=cost_of_holiday)

[['01578ed4e77', '1170', 'Geoje-Si', '487'],
 ['8992c78165', '1132', 'Geoje-Si', '587'],
 ['dac003fa56', '1258', 'Tubakuba', '408'],
 ['e6b32692e', '1254', 'Aalborg', '507'],
 ['1dbcfe08c3', '1368', 'Parowan', '207'],
 ['52c6f5bab4', '1305', 'Nullarbor', '605']]

In [384]:
[(h, cost_of_holiday(h)) for h in example_holidays]

[(['8992c78165', '1132', 'Geoje-Si', '587'], 1219),
 (['1dbcfe08c3', '1368', 'Parowan', '207'], 1368),
 (['52c6f5bab4', '1305', 'Nullarbor', '605'], 1410),
 (['e6b32692e', '1254', 'Aalborg', '507'], 1261),
 (['dac003fa56', '1258', 'Tubakuba', '408'], 1258),
 (['01578ed4e77', '1170', 'Geoje-Si', '487'], 1170)]

In [385]:
print('|      Holiday             | Price to you |')
print('|---------------------------------|-------|')
for h in example_holidays:
    print('|', '`' + ' '.join(h) + '`', '|', cost_of_holiday(h), '|')

|      Holiday             | Price to you |
|---------------------------------|-------|
| `8992c78165 1132 Geoje-Si 587` | 1219 |
| `1dbcfe08c3 1368 Parowan 207` | 1368 |
| `52c6f5bab4 1305 Nullarbor 605` | 1410 |
| `e6b32692e 1254 Aalborg 507` | 1261 |
| `dac003fa56 1258 Tubakuba 408` | 1258 |
| `01578ed4e77 1170 Geoje-Si 487` | 1170 |
